import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'

import './globals.css'
import { cx } from '@/lib/actions/utility'

const sourceSans = Source_Sans_3({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const bc = cx(
    sourceSans.className,
    'v-screen h-screen bg-gradient-to-r from-purple-900 to-blue-900 text-white'
  )

  return (
    <html lang='en'>
      <body className={bc}>
        <nav className='bg-gradient-to-r from-purple-700 to-blue-700'>
          <h2 className='p-4 text-2xl font-bold'>Channels</h2>
        </nav>

        <main className='py-2'>{children}</main>
      </body>
    </html>
  )
}
